language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
  - nosetests tests -v --with-coverage --cover-inclusive --cover-package=ndex2
